name: "Install LLVM and Clang"
description: "Downloads and installs LLVM and Clang binaries."

branding:
  icon: "arrow-down-circle"
  color: "black"

inputs:
  version:
    description: "The version of LLVM and Clang binaries to install."
    required: true
  force-version:
    description: "Whether to accept unsupported LLVM and Clang versions."
    required: false
  ubuntu-version:
    description: "The version override of Ubuntu to use for the Linux platform."
    required: false
  directory:
    description: "The directory to install LLVM and Clang binaries to."
    required: false
  cached:
    description: "Whether the LLVM and Clang binaries were cached."
    required: false
  download-url:
    description: "The URL to download LLVM and Clang binaries from."
    required: false
  auth:
    description: "The auth header value to use when downloading LLVM and Clang binaries."
    required: false

outputs:
  version:
    description: "The full version of LLVM and Clang binaries installed."

runs:
  using: "node12"
  main: "dist/index.js"
